dist: focal
language: c

os: linux

compiler: gcc


script:
    # скрипт сборки и тестирования проекта:
    - cd project/
    - mkdir build
    - cd build
    - cmake ..
    - make clean && make
    - ctest
    - ./tests/test_tests
    - valgrind --tool=memcheck --leak-check=full ./tests/test_tests
    - ctest --output-on-failure
