dist: focal
language: cpp

os: linux

compiler: gcc

install:
    - sudo apt-get install valgrind
    - sudo apt-get install cppcheck

script:
    # скрипт сборки и тестирования проекта:
    - cd project/
    - mkdir build
    - cd build
    - cmake ..
    - make clean && make
    - ctest --output-on-failure
    - valgrind --tool=memcheck --leak-check=full ./tests/test_tests
