dist: focal
language: cpp

os: linux

compiler: gcc

install:
    - sudo apt-get install valgrind
    - sudo apt-get install cppcheck

script:
    - cd project/
    - mkdir build
    - cd build
    - cmake ..
    - make clean && make
    - valgrind --tool=memcheck --leak-check=full ./tests/test1_tests
    - valgrind --tool=memcheck --leak-check=full ./tests/test2_tests
